Write-Host "Setting up ADE..." -ForegroundColor Green
Write-Host ""

# =========================
# Base Path
# =========================
$ADE_BASE = (Get-Location).Path
Write-Host "ADE_BASE: $ADE_BASE"

# =========================
# Ensure projects
# =========================
New-Item -ItemType Directory -Force -Path "$ADE_BASE\projects" | Out-Null
New-Item -ItemType File -Force -Path "$ADE_BASE\projects\.keep" | Out-Null

# =========================
# Setup env
# =========================
$envFile = "$ADE_BASE\ai_dev_env\config\env.sh"
$sampleFile = "$ADE_BASE\ai_dev_env\config\env.sample.sh"

if (!(Test-Path $envFile)) {
    Copy-Item $sampleFile $envFile
    Write-Host "Created env.sh"
}

# =========================
# Python selection
# =========================
$PY_VERSION = $env:ADE_PYTHON_VERSION
if (-not $PY_VERSION) { $PY_VERSION = "3.11" }

$PYTHON = ""

Write-Host "Selecting Python ($PY_VERSION)..."

try {
    py -$PY_VERSION -c "print('ok')" 2>$null | Out-Null
    $PYTHON = "py -$PY_VERSION"
} catch {
    Write-Host "Preferred Python not found, fallback..."

    foreach ($v in @("3.12","3.11","3.10")) {
        try {
            py -$v -c "print('ok')" 2>$null | Out-Null
            $PYTHON = "py -$v"
            break
        } catch {}
    }
}

if (-not $PYTHON) {
    if (Get-Command python -ErrorAction SilentlyContinue) {
        $PYTHON = "python"
    } else {
        Write-Host "ERROR: No Python found" -ForegroundColor Red
        exit 1
    }
}

Write-Host "Using Python: $PYTHON"

# =========================
# Create ADE venv
# =========================
$venvPath = "$ADE_BASE\venv"

if (!(Test-Path $venvPath)) {
    & $PYTHON -m venv $venvPath
}

$pythonExe = "$venvPath\Scripts\python.exe"

# =========================
# Install deps
# =========================
& $pythonExe -m pip install --upgrade pip setuptools wheel
& $pythonExe -m pip install --upgrade aider-chat

# =========================
# Ollama check
# =========================
if (!(Get-Command ollama -ErrorAction SilentlyContinue)) {
    Write-Host "WARNING: Ollama not found"
} else {
    Write-Host "Ollama detected"
}

# =========================
# Managed Profile Block
# =========================
$profilePath = $PROFILE

if (!(Test-Path $profilePath)) {
    New-Item -ItemType File -Path $profilePath -Force | Out-Null
}

$content = Get-Content $profilePath -Raw

# Remove old ADE block
$content = $content -replace "(?s)# >>> ADE START >>>.*?# <<< ADE END <<<", ""

# Write cleaned content
Set-Content $profilePath $content

# Append fresh block
Add-Content $profilePath @"
# >>> ADE START >>>
# ⚠️ AUTO-GENERATED BY ADE
# ⚠️ DO NOT EDIT THIS BLOCK MANUALLY
# ⚠️ RUN setup.sh TO UPDATE

`$env:ADE_BASE = "$ADE_BASE"

function runai {
    & "$env:ADE_BASE\venv\Scripts\activate.ps1"
    bash "$env:ADE_BASE/ai_dev_env/scripts/run_aider.sh" @args
}

function newproj {
    & "$env:ADE_BASE\venv\Scripts\activate.ps1"
    bash "$env:ADE_BASE/ai_dev_env/scripts/create_project.sh" @args
}
# <<< ADE END <<<
"@

Write-Host ""
Write-Host "INFO: ADE manages a block inside your PowerShell profile:" -ForegroundColor Cyan
Write-Host "$PROFILE"
Write-Host ""

. $PROFILE

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
