#!/bin/bash

echo "Setting up ADE..."
echo ""

ADE_BASE="$(pwd)"
echo "ADE_BASE: $ADE_BASE"

# =========================
# ⚠️ Path warning
# =========================
if [[ "$ADE_BASE" == *" "* ]]; then
  echo "WARNING: Path contains spaces. May cause issues."
fi

# =========================
# 📁 Ensure projects folder
# =========================
mkdir -p "$ADE_BASE/projects"
touch "$ADE_BASE/projects/.keep"

# =========================
# ⚙️ Setup env.sh
# =========================
ENV_FILE="$ADE_BASE/ai_dev_env/config/env.sh"
SAMPLE_FILE="$ADE_BASE/ai_dev_env/config/env.sample.sh"

if [ ! -f "$ENV_FILE" ]; then
  cp "$SAMPLE_FILE" "$ENV_FILE"
  echo "Created env.sh from sample"
fi

# Load env
source "$ENV_FILE"

# =========================
# 🐍 DETACHED PYTHON SELECT
# =========================
PY_VERSION="${ADE_PYTHON_VERSION:-3.11}"
PYTHON_BIN=""

echo "Selecting Python ($PY_VERSION)..."

# Try preferred version
if command -v python$PY_VERSION &> /dev/null; then
  PYTHON_BIN="python$PY_VERSION"
else
  echo "Preferred Python not found, falling back..."

  for v in 3.12 3.11 3.10; do
    if command -v python$v &> /dev/null; then
      PYTHON_BIN="python$v"
      break
    fi
  done
fi

# Final fallback
if [ -z "$PYTHON_BIN" ]; then
  if command -v python3 &> /dev/null; then
    PYTHON_BIN="python3"
  else
    echo "❌ No Python found"
    exit 1
  fi
fi

echo "Using Python: $PYTHON_BIN"

# =========================
# 🧪 ADE VENV
# =========================
if [ ! -d "$ADE_BASE/.venv" ]; then
  echo "Creating ADE venv..."
  $PYTHON_BIN -m venv "$ADE_BASE/.venv"
fi

source "$ADE_BASE/.venv/bin/activate"

# =========================
# 📦 Install core deps
# =========================
echo "Upgrading pip..."
python -m pip install --upgrade pip setuptools wheel

echo "Installing aider..."
pip install --upgrade aider-chat

# =========================
# 🤖 Ollama check
# =========================
if ! command -v ollama &> /dev/null; then
  echo "WARNING: Ollama not found!"
else
  echo "Ollama found"
fi

# =========================
# 📝 Managed Bashrc Block
# =========================
BASHRC="$HOME/.bashrc"

# Remove old ADE block
sed -i '/# >>> ADE START >>>/,/# <<< ADE END <<</d' "$BASHRC"

# Add fresh block
cat <<EOF >> "$BASHRC"

# >>> ADE START >>>
# ⚠️ AUTO-GENERATED BY ADE
# ⚠️ DO NOT EDIT THIS BLOCK MANUALLY
# ⚠️ RUN setup.sh TO UPDATE

export ADE_BASE="$ADE_BASE"
source "\$ADE_BASE/ai_dev_env/config/env.sh"

runai() {
  source "\$ADE_BASE/.venv/bin/activate"
  "\$ADE_BASE/ai_dev_env/scripts/runai.sh" "\$@"
}

newproj() {
  source "\$ADE_BASE/.venv/bin/activate"
  "\$ADE_BASE/ai_dev_env/scripts/newproj.sh" "\$@"
}
# <<< ADE END <<<
EOF

echo "ℹ️ ADE manages a block inside your shell config (~/.bashrc)"

echo ""
echo "Reloading..."
source "$HOME/.bashrc"

echo ""
echo "Setup complete!"
