#!/usr/bin/env bash
# ============================================================
# newproj — ADE Project Scaffolding CLI
# Usage: newproj <project_name> --type django|fastapi
# ============================================================
set -euo pipefail

# ── Colours ─────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[ADE]${RESET} $*"; }
success() { echo -e "${GREEN}✅${RESET} $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
error()   { echo -e "${RED}✗${RESET}  $*" >&2; exit 1; }

# ── Defaults ─────────────────────────────────────────────────
PROJECT_TYPE="django"
PROJECT_NAME=""

# ── Arg Parsing ──────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
    echo "Usage: newproj <project_name> [--type django|fastapi]"
    exit 1
fi

PROJECT_NAME="$1"; shift

while [[ $# -gt 0 ]]; do
    case "$1" in
        --type) PROJECT_TYPE="$2"; shift 2 ;;
        *)      error "Unknown argument: $1" ;;
    esac
done

# ── Validate env ─────────────────────────────────────────────
ADE_PROJECTS="${ADE_PROJECTS:-$HOME/hub/00_own/ADE/projects}"
PROJECT_PATH="$ADE_PROJECTS/$PROJECT_NAME"

if [[ -d "$PROJECT_PATH" ]]; then
    error "Project '$PROJECT_NAME' already exists at $PROJECT_PATH"
fi

echo ""
echo -e "${BOLD}🚀 ADE — New Project${RESET}"
echo -e "   Name : ${CYAN}${PROJECT_NAME}${RESET}"
echo -e "   Type : ${CYAN}${PROJECT_TYPE}${RESET}"
echo -e "   Path : ${CYAN}${PROJECT_PATH}${RESET}"
echo ""

mkdir -p "$PROJECT_PATH"
cd "$PROJECT_PATH"

# ── Python venv ──────────────────────────────────────────────
info "Creating Python virtual environment..."
python3 -m venv .venv
source .venv/bin/activate

# ── Scaffold by type ─────────────────────────────────────────
case "$PROJECT_TYPE" in
    django)
        info "Installing Django + DRF..."
        pip install -q django djangorestframework pytest pytest-django

        info "Scaffolding Django project..."
        django-admin startproject config .
        python manage.py startapp core

        # Patch INSTALLED_APPS
        sed -i "s/'django.contrib.staticfiles',/'django.contrib.staticfiles',\n    'rest_framework',\n    'core',/" config/settings.py

        # Minimal pytest config
        cat > pytest.ini <<'EOF'
[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests/*.py
EOF
        # Minimal conftest
        cat > conftest.py <<'EOF'
import django
from django.conf import settings
EOF

        # Placeholder test
        mkdir -p tests
        cat > tests/__init__.py <<'EOF'
EOF
        cat > tests/test_placeholder.py <<EOF
# Auto-generated by ADE newproj
def test_project_created():
    assert True, "Project scaffolded successfully"
EOF
        ;;

    fastapi)
        info "Installing FastAPI + Uvicorn..."
        pip install -q fastapi uvicorn pytest httpx

        info "Scaffolding FastAPI project..."
        mkdir -p app/routers app/models app/schemas tests
        touch app/__init__.py app/routers/__init__.py app/models/__init__.py app/schemas/__init__.py

        cat > app/main.py <<'EOF'
from fastapi import FastAPI

app = FastAPI(title="ADE FastAPI Project")

@app.get("/health")
def health():
    return {"status": "ok"}
EOF
        cat > tests/test_main.py <<'EOF'
from httpx import AsyncClient
from app.main import app
import pytest

@pytest.mark.anyio
async def test_health():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        resp = await ac.get("/health")
    assert resp.status_code == 200
EOF
        ;;

    *)
        error "Unknown project type: '$PROJECT_TYPE'. Supported: django, fastapi"
        ;;
esac

# ── Git ──────────────────────────────────────────────────────
info "Initialising git repository..."
git init -q
echo ".venv/" >> .gitignore
echo "__pycache__/" >> .gitignore
echo "*.pyc" >> .gitignore
echo ".ade_index/" >> .gitignore
git add -A
git commit -q -m "chore: ADE initial scaffold ($PROJECT_TYPE)"

echo ""
success "Project '${PROJECT_NAME}' ready at ${PROJECT_PATH}"
echo ""
echo -e "  Next steps:"
echo -e "    ${CYAN}runai ${PROJECT_NAME} \"create a Product model with name and price\"${RESET}"
echo ""
